/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_HelloJNI */

#ifndef _Included_com_example_HelloJNI
#define _Included_com_example_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_HelloJNI
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_HelloJNI_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
