version: "3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    environment:
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
