spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:h2_vue
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
  output:
    ansi:
      enabled: always

